version: '3.8'

services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/config:/etc/nginx/conf.d
    ports:
      - '80:80'

  php-fpm:
    build:
      context: .docker/php-fpm
    image: reofap-php-fpm
    container_name: php-fpm
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./.docker/php-fpm/config/general.ini:/usr/local/etc/php/conf.d/general.ini
      - ./.docker/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=reofap.test"

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    depends_on:
      - nginx

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 234451
      MYSQL_DATABASE: renovation_of_apartments
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 157266
    ports:
      - '127.0.0.1:3306:3306'

networks:
  default:
    name: reofap-net

volumes:
  mysql-data:
    name: mysql-data
