version: '3.7'

services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    ports:
      - '127.0.0.1:80:80'

  php-fpm:
    build:
      context: ./
      dockerfile: php-fpm.dev.dockerfile
    image: reofap-php-fpm
    container_name: php-fpm
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/config/general.ini:/usr/local/etc/php/conf.d/general.ini
      - ./docker/php-fpm/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    #  - ./docker/php-fpm/xdebug/log/remote.log:/var/log/xdebug/remote.log

  memcached:
    image: memcached:1.5
    container_name: memcached
    depends_on:
      - nginx

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 234451
      MYSQL_DATABASE: renovation_of_apartments
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 157266

networks:
  default:
    name: reofap-net

volumes:
  mysql-data:
    name: mysql-data
